// Server.js - This file is the initial starting point for the Node/Express server.

// Dependencies
const express = require('express');
require('dotenv').config();

// Sets up the Express App
const app = express();
const PORT = process.env.PORT || 8080;

// Sets up the Express app to handle data parsing
app.use(express.urlencoded({ extended: true }));
app.use(express.json());

// Static directory
app.use(express.static('app/public'));

// Routes
require('./routes/api-routes.js')(app);
require('./routes/html-routes.js')(app);

// Starts the server to begin listening
app.listen(PORT, () => console.log(`Listening on PORT ${PORT}`));

const cloudinary = require('cloudinary').v2;


cloudinary.config({ 
    cloud_name: process.env.CLOUD_NAME,
    api_key: process.env.API_KEY,
    api_secret: process.env.API_SECRET
  });


  cloudinary.uploader.upload("./noteTakerSave.png", function(error, result) {console.log(result, error)});

// File upload
//cloudinary.uploader.upload('./pic3.jpg', { tags: 'basic_sample' }, function (err, image) {
//    console.log();
//    console.log("** File Upload");
//    if (err) { console.warn(err); }
//    console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
//    console.log("* " + image.public_id);
//    console.log("* " + image.url);
//  });